[package]
name = "mattr"
version = "1.0.1"
authors = ["Elliott Mahler <join.together@gmail.com>"]
edition = "2021"
description = "Utility for transposing multi-dimensional data"
license = "MIT OR Apache-2.0"

repository = "https://github.com/bend-n/transpose"
keywords = ["array", "transpose", "2d"]
categories = ["algorithms", "data-structures", "no-std"]
readme = "README.md"

[[bench]]
name = "transpose_benchmarks"
harness = false
